# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4392d60c9456596c0d3c49a787784e9b4bd873a5b13f82c9a13a9520992b876c9800448ede748215a3d62ad2c1e9919b5053806fe0f51db7185d028a10806bf

test:
  secret_key_base: 2a91de3d2c6bc181cfa9024df49416d99a0d1a7db7a4eb565e59403ad4e0a0f761afdf84996ba8dae5902a5e7fd3c6620032d543cdcab8356be9687687d6b4a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
