# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e781758a341416cabcf5187e9d21669c541c7e34a7cb379e7f07b826b916850ed7125fa343a4a47497b80175baf049e2de24d9078bb6ebb5875ff02858f2f5f8

test:
  secret_key_base: da6bf118e7bb3da8700306d764a99ae6b54ec4dbc8a539e91c7834f977b759ed1bcd409c5ef3d7058ce845f478e0458f6169390470018fa815e1a479980fd9d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
